# Generated by Django 5.1.4 on 2024-12-08 14:43

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url_id', models.CharField(db_index=True, max_length=128)),
                ('long_url', models.URLField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateField(db_index=True, default=main.models.get_expiration_date)),
            ],
        ),
    ]
