# Generated by Django 5.1.4 on 2024-12-08 14:52

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='expiration_date',
            field=models.DateTimeField(db_index=True, default=main.models.get_expiration_date),
        ),
    ]
