# Generated by Django 5.1.4 on 2024-12-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_urlmapping_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmapping',
            name='id',
        ),
        migrations.AlterField(
            model_name='urlmapping',
            name='short_url_id',
            field=models.CharField(db_index=True, max_length=128, primary_key=True, serialize=False),
        ),
    ]
